[package]
name = "ch01_game_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#crate desc is 随机数库（下载依赖会被该库的上层依赖下载一遍，如Rand依赖上层的libc.）
#下载的是0.7.X（默认是最新版本）
rand = "0.8.5"